services:
  orderapi:
    image: orderapi
    build:
      context: .
      dockerfile: OrderAPI/Dockerfile
    ports:
      - 31045:8080

  productapi:
    image: productapi
    build:
      context: .
      dockerfile: ProductAPI/Dockerfile
    ports:
      - 8002:8080

  promotionsapi:
    image: promotionsapi
    build:
      context: .
      dockerfile: PromotionsAPI/Dockerfile
    ports:
      - 8003:8080

  reviewsapi:
    image: reviewsapi
    build:
      context: .
      dockerfile: ReviewsAPI/Dockerfile
    ports:
      - 8004:8080

  shippingapi:
    image: shippingapi
    build:
      context: .
      dockerfile: ShippingAPI/Dockerfile
    ports:
      - 8005:8080
        

